INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (1, 'Thioredoxin', 2, 105, 1);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (2, 'GMC oxidoreductase', 42, 352, 2);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (3, 'GMC oxidoreductase', 452, 593, 2);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (4, 'Methyltransferase', 7, 239, 3);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (5, 'ABC transporter', 41, 347, 4);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (6, 'Phosphotransferase', 51, 297, 5);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (7, 'CheR-type methyltransferase', 15, 286, 7);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (8, 'Rhodopsin receptor', 50, 326, 8);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (9, 'G-alpha', 32, 354, 9);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (10, 'G-alpha', 32, 354, 10);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (11, 'Methyltransferase', 99, 210, 11);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (12, 'TaqI Like', 291, 405, 11);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (13, 'SAM-dependent MTase C5-type', 12, 325, 12);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (14, 'SAM-dependent MTase C5-type', 12, 325, 13);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (15, 'Crispr', 2, 459, 14);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (16, 'Initiation factor', 15, 77, 15);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (17, 'Initiation factor', 15, 77, 16);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (18, 'Chaperone', 6, 118, 17);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (19, 'Chaperone', 6, 118, 18);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (20, 'Enterocin A immunity', 17, 76, 19);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (21, 'TPS secretion', 36, 212, 20);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (22, 'TPS secretion', 36, 212, 21);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (23, 'Thioredoxin', 1, 105, 22);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (24, 'Thioredoxin', 1, 105, 23);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (25, 'Phosphoglycerate kinase', 9, 404, 25);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (26, 'Phosphoglycerate kinase', 9, 404, 26);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (27, 'Serpin', 1, 70, 30);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (28, 'Serpin', 1, 70, 31);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (29, 'MPN', 2182, 2311, 33);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (30, 'snRNA intercating', 1514, 1671, 33);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (31, 'Recognition motif of spliceosome', 1059, 1149, 33);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (32, 'Helicase ATP-binding', 23, 408, 34);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (33, 'Helicase C-terminal', 425, 591, 34);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (34, 'UVR', 611, 646, 34);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (35, 'Insulin', 28, 50, 35);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (36, 'Insulin', 28, 109, 36);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (37, 'Peptidase S1', 9, 229, 37);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (38, 'Peptidase S1', 24, 244, 38);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (39, 'NR LBD', 163, 407, 39);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (40, 'NNMT', 16, 279, 40);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (41, 'ATP Synthase', 1, 79, 41);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (42, 'YiDC perisplasmic', 61, 343, 42);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (43, '60Kd inner membrane protein', 354, 533, 42);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (44, 'bHLH', 369, 421, 43);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (45, 'bZIP', 225, 281, 44);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (46, 'FERM', 34, 420, 45);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (47, 'FERM', 34, 420, 45);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (48, 'FERM', 34, 420, 45);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (49, 'FERM', 34, 420, 45);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (50, 'FERM', 37, 380, 46);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (51, 'Protein kinase 1', 545, 809, 46);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (52, 'Protein kinase 2', 849, 1124, 46);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (53, 'PDZ 1', 258, 349, 47);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (54, 'PDZ 2', 355, 447, 47);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (55, 'C-type lysozyme', 19, 147, 48);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (56, 'C-type lysozyme', 19, 147, 49);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (57, 'C-type lysozyme', 19, 147, 50);
INSERT INTO DOMAINE (id, nom, debut, fin, id_proteine) VALUES (58, 'SH2', 401, 482, 50);
