INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Archaea', 'None', 'None', 'Methanocaldococcus', 'jannaschii', 1);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Archaea', 'None', 'None', 'Saccharolobus', 'solfataricus', 2);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'Homo sapiens', 'Treponema', 'pallidum', 3);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '+', 'None', 'Bacillus', 'subtilis', 4);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'None', 'Salmonella', 'enterica', 5);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'None', 'Thermus', 'aquaticus', 6);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'Homo sapiens', 'Haemophilus', 'haemolyticus', 7);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'Homo sapiens', 'Haemophilus', 'parahaemolyticus', 7);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'Homo sapiens', 'Escherichia', 'coli', 8);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'Sus scrofa', 'Yersinia', 'enterocolitica', 9);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'Rattus rattus', 'Yersinia', 'pestis', 9);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '+', 'Bos taurus', 'Lactococcus', 'lactis', 9);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'Homo sapiens', 'Enterobacter', 'cloacae', 8);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '+', 'None', 'Alicyclobacillus', 'acidocaldarius', 6);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Bacteria', '-', 'None', 'Thermus', 'thermophilus', 1);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Homo', 'sapiens', 10);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Aspergillus', 'niger', 11);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Rattus', 'norvegicus', 10);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Saccharomyces', 'cerevisiae', 11);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Bos', 'taurus', 10);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Sus', 'scrofa', 10);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Mus', 'musculus', 10);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Eukaryota', 'None', 'None', 'Gallus', 'gallus', 10);
INSERT INTO ORGANISME (phyla, gram, hote, genre, espece, id_habitat) VALUES ('Viruses', 'None', 'Escherichia coli', 'Tequatrovirus', 't4', 8);
