INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (1, 'OXIDOREDUCTASE', 'Thioredoxin', 11.75, 876, 105, 1, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (2, 'OXIDOREDUCTASE', 'Glucose oxidase', 65.91, 4774, 583, 1, 2);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (3, 'TRANSFERASE', 'DNA adenine methylase', 30.85, 2077, 259, 1, 3);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (4, 'TRANSPORT PROTEIN', 'Membrane lipoprotein TmpC', 34.33, 2635, 318, 1, 4);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (5, 'TRANSFERASE', 'Spore coat protein I', 82.22, 5615, 692, 1, 5);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (6, 'ACETYLCHOLINE RECEPTOR', 'Acetylcholine receptor subunit delta', 2.67, 57, 25, 1, 6);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (7, 'METHYLTRANSFERASE', 'Chemotaxis protein methyltransferase', 31.92, 2361, 274, 1, 7);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (8, 'MEMBRANE PROTEIN', 'Beta-2 adrenergic receptor', 121.06, 7207, 1062, 1, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (9, 'MEMBRANE PROTEIN', 'Guanine nucleotide-binding protein G(i) subunit alpha-1', 162.76, 9573, 1454, 6, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (10, 'SIGNALING PROTEIN', 'Guanine nucleotide-binding protein G(i) subunit alpha-1', 41.61, 2625, 360, 1, 6);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (11, 'METHYLTRANSFERASE', 'Adenine-specific methyltransferase TaqI', 96.63, 6322, 842, 1, 8);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (12, 'TRANSFERASE-DNA', 'Cytosine-specific methyltransferase HhaI', 44.77, 3254, 351, 1, 9);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (13, 'TRANSFERASE-DNA', 'Cytosine-specific methyltransferase HhaI', 45.41, 379, 351, 1, 10);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (14, 'RNA BINDING PROTEIN-RNA', 'CRISPR system Cascade subunit CasA', 802.61, 54555, 6972, 5, 11);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (15, 'INITIATION FACTOR', 'Translation initiation factor 5A', 14.52, 106, 135, 1, 12);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (16, 'GENE REGULATION', 'Translation initiation factor 5A', 14.65, 110, 136, 1, 12);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (17, 'CHAPERONE', 'YopE regulator', 59.36, 4039, 528, 1, 13);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (18, 'CHAPERONE', 'YopE regulator', 32.7, 2161, 282, 1, 14);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (19, 'IMMUNE SYSTEM', 'Lactococcin-A immunity protein', 13.27, 931, 117, 1, 15);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (20, 'TOXIN', 'CdiA-ECL', 43.35, 1821, 390, 2, 16);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (21, 'TOXIN-ANTITOXIN', 'Toxin CdiA', 30.94, 2319, 272, 2, 11);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (22, 'ELECTRON TRANSPORT', 'Thioredoxin', 11.59, 812, 105, 1, 17);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (23, 'ELECTRON TRANSPORT', 'Thioredoxin', 93.85, 7202, 840, 1, 17);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (24, 'OXIDOREDUCTASE', 'Thioredoxin', 11.49, 805, 105, 1, 17);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (25, 'TRANSFERASE', 'Phosphoglycerate kinase', 45.02, 3353, 416, 1, 18);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (26, 'TRANSFERASE', 'Phosphoglycerate kinase', 45.37, 3191, 416, 1, 18);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (27, 'SYNTHASE', 'Indole-3-glycerol phosphate synthase', 28.72, 2258, 248, 1, 19);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (28, 'METAL BINDING PROTEIN', 'Indole-3-glycerol phosphate synthase', 57.06, 4045, 498, 1, 19);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (29, 'LYASE', 'Indole-3-glycerol phosphate synthase', 30.23, 2445, 258, 1, 19);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (30, 'ATPASE INHIBITOR', 'Inhibitor of F(1)F(o)-ATPase', 38.38, 2037, 336, 1, 20);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (31, 'ATPASE INHIBITOR', 'Inhibitor of F(1)F(o)-ATPase', 10, 702, 82, 1, 20);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (32, 'RIBOSOME', 'Nucleic acid-binding protein NAB1A', 991.67, 55262, 5456, 19, 18);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (33, 'TRANSCRIPTION', 'Pre-mRNA-splicing factor 8', 1404.07, 7737, 11488, 25, 18);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (34, 'TRANSCRIPTION', 'UvrABC system protein B', 107.19, 7297, 940, 2, 21);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (35, 'HORMONE-GROWTH FACTOR', 'Insulin', 5.88, 483, 51, 2, 22);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (36, 'HORMONE', 'Insulin', 36.36, 2862, 312, 2, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (37, 'COMPLEX (PROTEINASE-INHIBITOR)', 'Trypsin', 43.19, 3042, 400, 2, 22);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (38, 'HYDROLASE', 'Beta-trypsin', 26.39, 1928, 246, 1, 20);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (39, 'MEMBRANE PROTEIN', 'Thyroid hormone receptor alpha', 30.44, 204, 263, 1, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (40, 'TRANSFERASE', 'Phenylethanolamine N-methyltransferase', 62.98, 4173, 564, 1, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (41, 'MEMBRANE PROTEIN', 'ATP synthase subunit c', 8.26, 575, 79, 1, 11);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (42, 'PROTEIN TRANSPORT', 'Membrane protein insertase YidC', 69.84, 552, 627, 2, 11);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (43, 'LEUCINE ZIPPER', 'Myc proto-oncogene protein', 7.62, 533, 68, 2, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (44, 'LEUCINE ZIPPER', 'General control transcription factor GCN4', 8.04, 546, 66, 1, 18);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (45, 'SIGNALING PROTEIN', 'Tyrosine-protein kinase JAK1', 293.23, 10844, 2516, 2, 23);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (46, 'Transferase-Transferase Inhibitor', 'Janus kinase 2', 76.67, 5118, 642, 1, 1);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (47, 'HYDROLASE-HYDROLASE', 'Periplasmic pH-dependent serine endoprotease DegQ', 560.84, 4749, 5361, 2, 11);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (48, 'HYDROLASE', 'Lysozyme C', 16.33, 1082, 147, 1, 24);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (49, 'HYDROLASE', 'Lysozyme C', 17.51, 1080, 147, 1, 24);
INSERT INTO PROTEINE (id, famille, nom, masse, atomes, taille, sous_unites, id_genome) VALUES (50, 'HYDROLASE', 'Lysozyme C', 14.56, 1190, 129, 1, 24);
